# Matrices
## Matrix is a two dimensional vector, values are stored in rows and cols.
##   It is useful to do math operation in a fast way merging matrix.

In [74]:
import numpy as np

In [75]:
# m1 <- matrix(1:16, ncol = 4, nrow = 4, byrow = TRUE)
m1 = np.array([range(1, 5), range(6, 10)])
m2 = np.array([list(reversed(range(6, 10))), list(reversed(range(1, 5)))])
m3 = m1 + 1
m1, m2, m3

(array([[1, 2, 3, 4],
        [6, 7, 8, 9]]),
 array([[9, 8, 7, 6],
        [4, 3, 2, 1]]),
 array([[ 2,  3,  4,  5],
        [ 7,  8,  9, 10]]))

In [76]:
print(m1.shape)

(2, 4)


In [77]:
print("Scalar addition: n ", m1 + 1)

Scalar addition: n  [[ 2  3  4  5]
 [ 7  8  9 10]]


In [78]:
print(m1+m2) #Addition

[[10 10 10 10]
 [10 10 10 10]]


In [79]:
print(m1*m2) #Multiplication

[[ 9 16 21 24]
 [24 21 16  9]]


In [80]:
print(m3-m1) #Subtraction

[[1 1 1 1]
 [1 1 1 1]]


In [81]:
m3 -= 1  #Subtraction

In [82]:
print(m3/m1) #Division

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
